name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  fluttertoast: ^2.1.1
  groovin_material_icons: ^1.1.5
  intl: 0.15.8
  image_picker: ^0.4.12+1
  city_pickers: ^0.1.13
  flutter_picker: ^1.0.10
  flutter_refresh : ^0.0.1
  flutter_swiper: ^1.0.6
  image_cropper: ^0.0.8

flutter:

  uses-material-design: true

  assets:
  - images/